### ISSUE TITLE
Too old to be a <1.0.0 release version

### ISSUE THREAD

**Issue by tim-win** [Deepwalker/trafaret#10]
I'd like to rely on this software for important world changing projects, but it's still in 0.X version which means minor version bumps include breaking changes which is not good.

Are there any plans to bump to 1.X so I can pin to `trafaret>=1,<2`? I'd like some sort of agreement of stability before I include start using this to change the world.

**Comment by Templarrr** [comment]
+1, let's start taking responsibilities about breaking changes.

**Comment by Deepwalker** [comment]
Ok guys. But before I will take this responsibility I need to make changes. I will not pin 1.0 while I have things that I dont like. And its not really helpful to complain about every change and ignore any deprecation warnings for 6 months.

**Comment by tim-win** [comment]
Yes, thank you! The entire DataRobot team is behind you on this.

**Comment by asvetlov** [comment]
I understand @Deepwalker concerns: aiohttp after 1.0 release has several breaking API changes.
On other hand claiming a stable release forces to change development process: deprecation warnings, stable API support etc.

**Comment by Deepwalker** [comment]
Ok, lets 1.0.0.
