### ISSUE TITLE
No FromString/ToBytes?

### ISSUE THREAD

**Issue by Dreamsorcerer** [Deepwalker/trafaret#104]
There is a FromBytes object to convert to string. It would be nice to have the inverse to convert to bytes.

**Comment by Deepwalker** [comment]
Do you have real use case? How it should look like?
`ToBytes(encoding='utf-8')`?

**Comment by Dreamsorcerer** [comment]
Looks reasonable, yes. Use case is to pass an argument such as a password into a password hashing function, which requires bytes.

```
login = t.Dict({"password": t.ToBytes(encoding="utf-8"), "username": t.String()})
hashlib.scrypt(login["password"], ...)
```
