### ISSUE TITLE
Latest version from PyPI does not align with master code 

### ISSUE THREAD

**Issue by sonerayberk** [Deepwalker/trafaret#112]
Steps to reproduce: 
- Install the latest version from PyPI (2.0.2)
- Go to trafaret/base - Dict class, method `merge` and see the following code:
<img width="700" alt="Снимок экрана 2020-09-09 в 16 26 44" src="https://user-images.githubusercontent.com/4007152/92604498-42189400-f2b9-11ea-8964-8f3d0bc3acb2.png">

Actual code in the master branch:
<img width="912" alt="Снимок экрана 2020-09-09 в 16 27 43" src="https://user-images.githubusercontent.com/4007152/92604627-65434380-f2b9-11ea-906d-82b8bc04eac4.png">

The issue with merge has been fixed here: https://github.com/Deepwalker/trafaret/pull/100

I guess you are the only one who can update the build :)

**Comment by Deepwalker** [comment]
v2.1.0 released
