### ISSUE TITLE
Is OK that `t.Int().check("1")` returns `'1'` not `1`?

### ISSUE THREAD

**Issue by VadymKhodak** [Deepwalker/trafaret#113]
**trafaret version 2.1.0:**
![image](https://user-images.githubusercontent.com/32848370/93069089-e9b11000-f685-11ea-91d7-6c1d8430292f.png)

**trafaret version 1.2.0:**
![image](https://user-images.githubusercontent.com/32848370/93069115-f03f8780-f685-11ea-90d4-f1d739b0c8bb.png)

**Comment by Deepwalker** [comment]
Yes. It was v2.0 when we introduced `ToInt`, `ToFloat` etc. So if you want old behaviour you should use `ToInt` now.

**Comment by VadymKhodak** [comment]
Thank you!
