### ISSUE TITLE
Changelog missed

### ISSUE THREAD

**Issue by playpauseandstop** [Deepwalker/trafaret#20]
Hi,

Recently you updated trafaret to 1.0 and there are completely no docs on what changed between 0.12.0 and 1.0.0 release.

Did you consider put this to `CHANGES.txt` or at least at GitHub releases page?

ps. There is kind of [changelog](https://github.com/Deepwalker/trafaret/blob/master/docs/changelog.rst) in docs, but it completely out-of-sync
pps. And yes, documentation for trafaret at RTFD still rendered for `0.10.4` version.

----

[Keep a Changelog](http://keepachangelog.com/en/1.0.0/) provides more information about how to make good Changelog for your users.

As usual thanks for trafaret, but let it be more developer friendly.

**Comment by Deepwalker** [comment]
ok, fixed
