### ISSUE TITLE
How to work with tuples in general?

### ISSUE THREAD

**Issue by ShT3ch** [Deepwalker/trafaret#23]
Hello. Here the case.

Maintainers of [aiozmq](https://github.com/aio-libs/aiozmq) library [recommend to use trafaret](https://aiozmq.readthedocs.io/en/v0.8.0/rpc.html#signature-validation) for type checking.
But also aiozmq's internals [convert all lists to tuples](https://aiozmq.readthedocs.io/en/v0.8.0/rpc.html#value-translators) while passing messages for RPC.

Trafaret's tuples take implicit types as parameter, but I'm not able just to receive tuple instead of list using trafaret.

For example:
```
import trafaret

recieved_msg = (1,2,3,4,5)

trafaret.Tuple(trafaret.Int).check(recieved_msg)
```
raises an error `DataError: {0: DataError(value must contain 1 items)}`

I'm not able to use `trafaret.List` too. It checks `isinstance(obj, list)`.

Can you suggest some workaround?

**Comment by Deepwalker** [comment]
Since it is too late to fix this in 1.x, I will check for Iterable in next release.
Meanwhile you can use something like `t.Type(tuple) & list & t.List(t.Int)`.
It will check that we have a tuple, then convert to list and now t.List can work.
