### ISSUE TITLE
Generate default config

### ISSUE THREAD

**Issue by runtel** [Deepwalker/trafaret#26]
Hi everybody!
Is it possible to save trafaret to yaml file as base config for apps?

**Comment by Deepwalker** [comment]
Trafaret are not any data structure, all trafarets are actually composed callables. Like `Regex`, `Int` and even a `Dict`. And what is important, `Dict` keys are actually callables too, but with other type signature.
So as you can see you cannot get any structure information from composed callables, and `save trafaret` operation is not possible.

But you can use a bit different approach. Lets make guess that you are talking about `Dict`. Then you can write something like:
```
my_trafaret_args = {
    'password': t.String(),
    'username': t.String(),
}
```
And then you can use like `my_trafaret_args.keys()` to generate this base config. Or you can create some code to make this for you. Trafaret will not help you with generation, it is one way, sorry.

**Comment by Deepwalker** [comment]
Since it is not an actual issue, I will close it ;) And you can try http://trafaret.readthedocs.io/en/latest/api/trafaret.constructor.html too.
Anyway, this task is for some derivative from trafaret, not for core library.
