### ISSUE TITLE
trafaret incompatible with python 3.7

### ISSUE THREAD

**Issue by samuelcolvin** [Deepwalker/trafaret#28]
https://travis-ci.org/samuelcolvin/pydantic/jobs/338604472

I think due to the use of `async` which is a reserved in py 3.7.

**Comment by Deepwalker** [comment]
Will solve it with 2.0 version that I'm baking right now.

**Comment by hellysmile** [comment]
What about quick rename hotfix ? minor patch?

**Comment by Deepwalker** [comment]
Of course. PR? It is fixed in version2 branch.

**Comment by Deepwalker** [comment]
1.2.0

**Comment by hellysmile** [comment]
thnx!!!
