### ISSUE TITLE
Why Dict.make_optional is deprecated?

### ISSUE THREAD

**Issue by KostyaEsmukov** [Deepwalker/trafaret#44]
I'm probably missing something out, but I'm wondering why was the `Dict.make_optional` method deprecated:
https://github.com/Deepwalker/trafaret/commit/c0d4e6d3aaf44d2bffb34282d86f3f73ec6d92b3#diff-a50b492e07b76174479082312cde9bd4R980

Suppose I have a large (I mean *really large*) dict where I need all keys to be optional. I personally find the currently-deprecated way of achieving this with `.make_optional('*')` [A] much more appealing than using explicit `Key(..., optional=True)` for each key [B]. Or maybe there already is a third non-deprecated method which is less cumbersome than [B] which I'm missing?

[A]:
```
mydict = t.Dict(
    a=t.Int,
    b=t.Int,
    ...
).make_optional('*')
```
[B]:
```
mydict = t.Dict({
    t.Key('a', optional=True): t.Int,
    t.Key('b', optional=True): t.Int,
    ...
})
```

**Comment by Deepwalker** [comment]
You can make it very simple without mutation of Keys instances. Something like `opt_key = lambda *a, **kw: t.Key(*a, optional=True, **kw)` will do the trick. The idea is that you must compose things, not make them overly configurable and complicated as result.

**Comment by KostyaEsmukov** [comment]
Yep, of course it's possible to make the [B] option look more pretty by introducing a new callable which returns a Key instance with an already set `optional=True`, be it a factory function, a subclass or a higher order function created with functools.

I was just hoping to keep the keyword args as in [A] without resorting to a dict as in [B].

Thank you for your response, I think this can be closed.
