### ISSUE TITLE
DeprecationWarning on import of abstract classes from collections

### ISSUE THREAD

**Issue by fly** [Deepwalker/trafaret#51]
In python 3.7 I'm getting the following deprecation warning:
```
DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
```

`collections.abc` is available starting from python 3.3.

Are there any plans on fixing it? (I guess you want to retain python2 support yet)

Also I don't mind to create PR to fix this. If you agree, do you have any preferred way this to be done?

**Comment by Deepwalker** [comment]
fixed it in version2 branch. Hope we will make release before 3.8

**Comment by asvetlov** [comment]
Please do.
Python relaxed the deprecation period to 3.9 but please take the warning seriously.
Now it requires an extra line in pytest configuration section for almost every project on my job :)

Would you consider `trafaret==1.2.1` bugfix release with fixed import?

**Comment by tirkarthi** [comment]
I guess this was fixed with https://github.com/Deepwalker/trafaret/pull/81 . Also the removal has been postponed to python 3.10.

**Comment by Deepwalker** [comment]
Tnx, forgot to close this after release.
