### ISSUE TITLE
Need to correct error message for Bytes checker

### ISSUE THREAD

**Issue by Arfey** [Deepwalker/trafaret#63]
```python
In [19]: t.Bytes().check(b'test') 
Out[19]: b'test'

In [18]: t.Bytes().check('test')
... 
DataError: value is not a string
```

In my opinion we need to change `string` to `bytes string`.

**Comment by tyulpan** [comment]
But isn't this code handling invalid values, or am I wrong?
https://github.com/Deepwalker/trafaret/blob/0f56dee366f583a59c7ebef1a64b3b4e4fdb6edd/trafaret/base.py#L629

**Comment by Arfey** [comment]
I put to `check` method string and after that receive error `value is not a string`.

**Comment by tyulpan** [comment]
I did the same and got:
```python
In [1]: base.Bytes().check(b'test') 
Out[1]: 'test'

In [2]: base.Bytes().check('test')
... 
DataError: Value is not bytes
```
But I did import as `import trafaret.base as base`, because the **Bytes** class isn't in the `__init__.py` file. That's why it seems to me that I am doing something wrong.

**Comment by Arfey** [comment]
```python
import trafaret as t

t.__VERSION__ 
(2, 0, '0-alpha.04')
```

**Comment by Arfey** [comment]
if u wanna install alpha version u can use that:

```
pip install https://github.com/Deepwalker/trafaret/archive/version2.zip
```

**Comment by tyulpan** [comment]
Yep, `DataError: value is not a string` :smile:

**Comment by Arfey** [comment]
thx :)
