### ISSUE TITLE
Add documentation about Iterable

### ISSUE THREAD

**Issue by Arfey** [Deepwalker/trafaret#71]
In version2 (branch) u need to add to introduction part documentation about `Iterable`.

For that u can use tests which connected with current part. As example u can use this [PR](https://github.com/Deepwalker/trafaret/pull/64).

Please don't forget:
-  your MR u need to do to the `version2` (branch)
- add screenshot with your part of documentation
- write below that u want to take it to work

**Comment by olya-zhulanova** [comment]
I take this

**Comment by Arfey** [comment]
good 👍

**Comment by Arfey** [comment]
what is up?

**Comment by Arfey** [comment]
https://github.com/Deepwalker/trafaret/pull/92
