### ISSUE TITLE
Remove `make_optional` from Dict.

### ISSUE THREAD

**Issue by Arfey** [Deepwalker/trafaret#78]

**Comment by tyulpan** [comment]
It's already removed. [link](https://github.com/Deepwalker/trafaret/commit/6956bd81c6ed7508790d4168f3df45df27a3e24a#diff-a50b492e07b76174479082312cde9bd4L1006-L1015)
Or am I misunderstood smth?

**Comment by Arfey** [comment]
Actually yes. I'll close this issue. Thx 👍
