### ISSUE TITLE
`extras.py` is still present on version 2.0.0

### ISSUE THREAD

**Issue by azhpushkin** [Deepwalker/trafaret#97]
Steps to reproduce: install latest version from pypi

![image](https://user-images.githubusercontent.com/17751432/68946367-7ddaee00-07bb-11ea-8ee0-9e61dbfd23b2.png)

There is no `extras.py` in source code anymore but it is still present after installation. This creates certain confusion as two versions of KeysSubset are present (in `keys.py` and extras).
Moreover, documentation is still pointing to the extras, which is even more confusing

**Comment by azhpushkin** [comment]
@Deepwalker This is not urgent at all, but I guess you are the only one who can update the build :crossed_fingers:

**Comment by Arfey** [comment]
thx for your contribution. MR u welcome.

**Comment by sonerayberk** [comment]
@Arfey I'm afraid, but isn't the build can be built and deployed to PyPI by the author of the library?

**Comment by Arfey** [comment]
Sure, but will be great if u fix documentation :)

**Comment by Deepwalker** [comment]
Have no idea how it happened. Issued 2.0.1.
